// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package headliner

type Articles []struct {
	// Headline corresponds to the JSON schema field "headline".
	Headline string `json:"headline"`
}
